# Clippy 配置文件

# 复杂度阈值 - 设置较宽松的阈值
cognitive-complexity-threshold = 50
too-many-arguments-threshold = 15
type-complexity-threshold = 1000
too-many-lines-threshold = 500

# 不允许的方法 - 只保留最关键的
disallowed-methods = []

# 不允许的类型 - 暂时为空，允许使用 HashMap
disallowed-types = []

# 其他配置
msrv = "1.70.0"
max-trait-bounds = 10
max-fn-params-bools = 5
max-struct-bools = 5
verbose-bit-mask-threshold = 16
enum-variant-name-threshold = 50
struct-field-name-threshold = 50
single-char-binding-names-threshold = 1
min-ident-chars-threshold = 1

# 允许的检查 - 针对Windows API使用
# 注意：clippy.toml 不直接支持 allow/deny，需要在代码中使用 #[allow(...)] 