# 代码格式化配置
edition = "2021"
max_width = 100
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Max"
match_block_trailing_comma = true
merge_derives = true
group_imports = "StdExternalCrate"
imports_granularity = "Module"
format_code_in_doc_comments = true
