coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%
    patch:
      default:
        target: 80%
        threshold: 1%

ignore:
  - "**/tests/**"
  - "**/benches/**"
  - "**/examples/**"
  - "**/target/**"
  - "**/build/**"
  - "**/docs/**"
  - "**/assets/**"

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false 