name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  # 核心代码质量检查（使用 nightly 版本支持项目特性）
  quality:
    name: Code Quality & Build
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install Rust (nightly)
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: rustfmt, clippy
      
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ runner.os }}-nightly-cargo-${{ hashFiles('**/Cargo.lock') }}
      
      - name: Check code formatting
        run: cargo fmt --all -- --check
      
      - name: Run Clippy (linter)
        run: cargo clippy --all-targets -- -D warnings
      
      - name: Build project
        run: cargo build --release --verbose
      
      - name: Run tests
        run: cargo test --verbose

  # 安全审计
  audit:
    name: Security Audit
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install Rust (nightly)
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
      
      - name: Install cargo-audit
        run: cargo install cargo-audit
      
      - name: Run security audit
        run: cargo audit 